version: '3'
services:
  postgres:
    container_name: postgres_container
    image: postgres:9.6.15
    environment:
      POSTGRES_USER: serj
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mdb
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: unless-stopped
  
  html_to_pdf:
    container_name: html_to_pdf
    image: openlabs/docker-wkhtmltopdf-aas
    restart: unless-stopped
    ports:
      - "32768:80"

volumes:
    postgres:


  