# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-07 09:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('order', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(max_length=150)),
                ('pdf_file', models.FileField(blank=True, max_length=150, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('api_key', models.CharField(max_length=150, unique=True)),
                ('check_type', models.CharField(max_length=150)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='printer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Printer'),
        ),
    ]
